version: 2.1

executors:
  arm-machine:
    machine:
      image: ubuntu-2204:2023.07.1
    resource_class: arm.medium

parameters:
  aws-oidc-role-arn:
    type: string
    default: arn:aws:iam::992382483259:role/kelvintaywl-oidc-ecr-public-read

orbs:
  aws-ecr: circleci/aws-ecr@9.0.3
  aws-cli: circleci/aws-cli@4.1.3

jobs:
  aws-example:
    environment:
      AWS_REGION: ap-northeast-1
      # no paging
      AWS_PAGER: ''
    executor: arm-machine
    steps:
      - checkout
      # run the aws-cli/setup command from the orb
      - aws-cli/setup:
          role_arn: << pipeline.parameters.aws-oidc-role-arn >>
          region: ${AWS_REGION}
          # optional parameters
          role_session_name: "test-session"
          session_duration: "1800"
      - run: aws sts get-caller-identity
      - aws-ecr/ecr_login:
          public_registry: true
          account_id: "992382483259"
          region: us-east-1
      - run: docker pull public.ecr.aws/o5b1w9d8/kelvintaywl-cci-cimg-base:latest
workflows:
  main:
    jobs:
      - aws-example:
          context:
            - foo-2
