version: 2.1

executors:
  arm-machine:
    machine:
      image: ubuntu-2204:2023.07.1
    resource_class: arm.medium
  amd-machine:
    machine:
      image: ubuntu-2204:current
    resource_class: medium

parameters:
  aws-oidc-role-arn:
    type: string
    default: arn:aws:iam::992382483259:role/kelvintaywl-server4-oidc-s3readonly
  # aws-ecr-image:
  #   type: string
  #   default: 992382483259.dkr.ecr.ap-northeast-1.amazonaws.com/kelvintaywl-cci-redis:6.2.5
  aws-region:
    type: string
    default: ap-northeast-1

orbs:
  aws-cli: circleci/aws-cli@4.1.3

jobs:
  aws-example:
    environment:
      AWS_REGION: << pipeline.parameters.aws-region >>
      # no paging
      AWS_PAGER: ''
      # see https://github.com/CircleCI-Public/aws-ecr-orb/pull/339/files
      BUILDX_NO_DEFAULT_ATTESTATIONS: 1
    machine: true
    steps:
      - aws-cli/setup:
          role_arn: << pipeline.parameters.aws-oidc-role-arn >>
          region: ${AWS_REGION}
          # optional parameters
          role_session_name: "test-session"
          session_duration: "1800"
      - run: aws sts get-caller-identity      
workflows:
  main:
    jobs:
      - aws-example:
          context:
            - foo
