version: 2.1

executors:
  arm-machine:
    machine:
      image: ubuntu-2204:2023.07.1
    resource_class: arm.medium

parameters:
  aws-oidc-role-arn:
    type: string
    default: arn:aws:iam::992382483259:role/kelvintaywl-oidc-ecr-readwrite
  aws-ecr-image:
    type: string
    default: 992382483259.dkr.ecr.ap-northeast-1.amazonaws.com/kelvintaywl-cci-redis:6.2.5
  aws-region:
    type: string
    default: ap-northeast-1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.2
  aws-cli: circleci/aws-cli@4.1.3

jobs:
  aws-example:
    environment:
      AWS_REGION: << pipeline.parameters.aws-region >>
      # no paging
      AWS_PAGER: ''
      # see https://github.com/CircleCI-Public/aws-ecr-orb/pull/339/files
      BUILDX_NO_DEFAULT_ATTESTATIONS: 1
    executor: arm-machine
    steps:
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                role_arn: << pipeline.parameters.aws-oidc-role-arn >>
                region: ${AWS_REGION}
                # optional parameters
                role_session_name: "test-session"
                session_duration: "1800"
            - run: aws sts get-caller-identity
          create_repo: false
          dockerfile: Dockerfile
          account_id: "992382483259"
          platform: linux/arm64
          region: << pipeline.parameters.aws-region >>
          repo: kelvintaywl-cci-redis
          tag: '${CIRCLE_SHA1}'        

      # - aws-ecr/ecr_login:
      #     public_registry: false
      #     account_id: "992382483259"
      #     region: << pipeline.parameters.aws-region >>
      # - run: docker pull << pipeline.parameters.aws-ecr-image >>
workflows:
  main:
    jobs:
      - aws-example:
          context:
            - foo-2
